version: "3"
services:
  mirai:
    image: lqbing/cqhttp-mirai
    restart: always
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - bot_net

  bot:
    image: lqbing/yoshino
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./data/log:/workdir/log
      - ./data/yobot_data:/workdir/hoshino/modules/yobot/yobot/src/client/yobot_data
      - ./data/static:/workdir/hoshino/modules/yobot/yobot/src/client/public/static/
      - ./data/res:/workdir/res
      - ./data/conf:/root/.hoshino
    networks:
      - bot_net

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/res:/workdir/res
    networks:
      - bot_net
networks:
  bot_net:
    driver: bridge
