version: "3"
services:

  cqhttp:
    image: richardchien/cqhttp:latest
    env_file: .env
    restart: on-failure
    volumes:
      - ./cqhttp:/home/user/coolq
    ports:
      - "9000:9000" # VNC端口
      # - "5700:5700" # HTTP API 插件开放的端口
    networks:
      - bot_net
      
  bot:
    image: lqbing/yoshino
    restart: always
    env_file: .env
    ports: 
      - 8000:8000
    volumes:
      - ./data/bot/log:/workdir/log
      - ./data/bot/yobot_data:/workdir/hoshino/modules/yobot/yobot/src/client/yobot_data
      - ./data/bot/static:/workdir/hoshino/modules/yobot/yobot/src/client/public/static/
      - ./data/bot/res:/workdir/res
      - ./data/bot/conf:/root/.hoshino
    networks:
      - bot_net

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/bot/res:/workdir/res
    networks:
      - bot_net
networks:
  bot_net:
    driver: bridge
